// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "config/data-structure.h"
#include "config/plui.h"
#include "config/string-format.h"
#include "config/type-undef.h"
#ifdef __cplusplus
}
#endif
