// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "config/alloc.h"
#include "config/check.h"
#include "config/data-structure.h"
#include "config/log.h"
#include "config/plos.h"
#include "config/plui.h"
#include "config/string-format.h"
#include "config/undef.h"
#ifdef __cplusplus
}
#endif
