// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "define/00-include.h"
#include "define/assert.h"
#include "define/attribute.h"
#include "define/base.h"
#include "define/int.h"
#include "define/logging.h"
#include "define/magic.h"
#include "define/mem.h"
#include "define/new.h"
#include "define/rc.h"
#include "define/va.h"
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
#include "define/00-include.hpp"
#include "define/assert.hpp"
#endif
