// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "type/00-include.h"
#include "type/atom-func.h"
#include "type/atom-lockfree.h"
#include "type/atom-type.h"
#include "type/atom.h"
#include "type/base.h"
#include "type/bool.h"
#include "type/char.h"
#include "type/complex.h"
#include "type/const.h"
#include "type/ex.h"
#include "type/func.h"
#include "type/int.h"
#include "type/limit.h"
#include "type/vector.h"
#ifdef __cplusplus
}
#endif
