// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "type/00-include.hpp"
#include "type/type.hpp"
#include "type/type_traits.hpp"
