// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "type/00-include.h"
#include "type/type.h"
#ifdef __cplusplus
}
#endif
