// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "zstd/zdict.h"
#include "zstd/zstd.h"
#include "zstd/zstd_errors.h"
#ifdef __cplusplus
}
#endif
