// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "asm/asm.h"
#include "asm/cpuid.h"
#include "asm/cpuid/funcs.h"
#include "asm/cpuid/ids.h"
#include "asm/cpuid/macros.h"
#include "asm/cr.h"
#include "asm/io.h"
#include "asm/mem.h"
#include "asm/msr.h"
#include "asm/reg.h"
#include "asm/syscall.h"
#ifdef __cplusplus
}
#endif
