// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "points/col.hpp"
#include "points/line.hpp"
#include "points/rect.hpp"
#include "points/row.hpp"
#include "points/triangle.hpp"
