// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "server/00-include.hpp"
#include "server/api.hpp"
#include "server/var.hpp"
