// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "asm/asm.h"
#include "asm/flag.h"
#include "asm/io.h"
#include "asm/syscall-linux-x64.h"
#ifdef __cplusplus
}
#endif
