// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "asm/asm.h"
#include "asm/cpuid.h"
#include "asm/cr.h"
#include "asm/flag.h"
#include "asm/io.h"
#include "asm/reg.h"
#include "asm/syscall-plos.h"
#ifdef __cplusplus
}
#endif
