// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "algorithm/base.h"
#include "algorithm/bm.h"
#include "algorithm/kmp.h"
#ifdef __cplusplus
}
#endif
