// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "config/debug.h"
#include "config/plui.h"
#include "config/string-format.h"
#ifdef __cplusplus
}
#endif
