// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "data-structure/atomic/event.h"
#include "data-structure/atomic/queue-mt.h"
#include "data-structure/base.h"
#include "data-structure/kernel/kqueue.h"
#include "data-structure/ordered-map/slist-strptr.h"
#include "data-structure/ordered-set/array-list.h"
#include "data-structure/ordered-set/bitmap.h"
#include "data-structure/ordered-set/circular-buffer.h"
#include "data-structure/ordered-set/circular-queue.h"
#include "data-structure/ordered-set/list.h"
#include "data-structure/ordered-set/mbitstream.h"
#include "data-structure/ordered-set/mstream.h"
#include "data-structure/ordered-set/queue.h"
#include "data-structure/ordered-set/slist.h"
#include "data-structure/sorted-map/avltree.h"
#include "data-structure/sorted-map/rbtree-strptr.h"
#include "data-structure/sorted-map/rbtree.h"
#include "data-structure/sorted-map/trie.h"
#include "data-structure/unordered-map/st.h"
#ifdef __cplusplus
}
#endif
