// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "define/define/00-include.hpp"
#include "define/define/assert.hpp"
#include "define/type/00-include.hpp"
#include "define/type/type.hpp"
#include "define/type/type_traits.hpp"
