// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "define/config/data-structure.h"
#include "define/config/plui.h"
#include "define/config/string-format.h"
#include "define/config/type-undef.h"
#include "define/define.h"
#include "define/type.h"
#ifdef __cplusplus
}
#endif
