// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "define/config/check.h"
#include "define/config/data-structure.h"
#include "define/config/log.h"
#include "define/config/plui.h"
#include "define/config/string-format.h"
#include "define/config/type-undef.h"
#include "define/define/00-include.h"
#include "define/define/assert.h"
#include "define/define/attribute.h"
#include "define/define/base.h"
#include "define/define/logging.h"
#include "define/define/magic.h"
#include "define/define/rc.h"
#include "define/define/va.h"
#include "define/type/00-include.h"
#include "define/type/type.h"
#ifdef __cplusplus
}
#endif
