// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "fs/include.h"
#include "fs/vfs.h"
#ifdef __cplusplus
}
#endif
