// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "kernel/8295a.h"
#include "kernel/cpu.h"
#include "kernel/dma.h"
#include "kernel/elf.h"
#include "kernel/fat.h"
#include "kernel/fdc.h"
#include "kernel/include-libc.h"
#include "kernel/ipc.h"
#include "kernel/lock.h"
#include "kernel/log.h"
#include "kernel/mem.h"
#include "kernel/mtask.h"
#include "kernel/os.h"
#include "kernel/page.h"
#include "kernel/ps2.h"
#include "kernel/sb16.h"
#include "kernel/screen.h"
#include "kernel/timer.h"
#include "kernel/tty.h"
#include "kernel/vbe.h"
#include "kernel/vdisk.h"
#include "kernel/vfs.h"
#ifdef __cplusplus
}
#endif
