// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "kernel/include-libc.h"
#include "kernel/os.h"
#ifdef __cplusplus
}
#endif
