// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "kernel/00-include.h"
#include "kernel/8259a.h"
#include "kernel/acpi.h"
#include "kernel/ahci.h"
#include "kernel/assert.h"
#include "kernel/cpu.h"
#include "kernel/dma.h"
#include "kernel/elf.h"
#include "kernel/fat.h"
#include "kernel/fdc.h"
#include "kernel/ipc.h"
#include "kernel/logging.h"
#include "kernel/mem.h"
#include "kernel/mtask.h"
#include "kernel/os.h"
#include "kernel/page.h"
#include "kernel/pci.h"
#include "kernel/ps2.h"
#include "kernel/screen.h"
#include "kernel/shared.h"
#include "kernel/sound.h"
#include "kernel/syscall.h"
#include "kernel/timer.h"
#include "kernel/tty.h"
#include "kernel/vbe.h"
#include "kernel/vdisk.h"
#include "kernel/vsound.h"
#ifdef __cplusplus
}
#endif
