// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "libc-base/arg.h"
#include "libc-base/asm/asm.h"
#include "libc-base/asm/cpuid.h"
#include "libc-base/asm/cr.h"
#include "libc-base/asm/flag.h"
#include "libc-base/asm/io.h"
#include "libc-base/asm/reg.h"
#include "libc-base/asm/syscall.h"
#include "libc-base/crypto/hash.h"
#include "libc-base/include.h"
#include "libc-base/math/base.h"
#include "libc-base/math/bits.h"
#include "libc-base/math/complex/base.h"
#include "libc-base/math/exp-log.h"
#include "libc-base/math/float.h"
#include "libc-base/math/i64-div.h"
#include "libc-base/math/math.h"
#include "libc-base/math/sqrt.h"
#include "libc-base/stdio/print.h"
#include "libc-base/stdlib/alloc.h"
#include "libc-base/stdlib/atox.h"
#include "libc-base/stdlib/rand.h"
#include "libc-base/stdlib/xtoa.h"
#include "libc-base/string/alloc.h"
#include "libc-base/string/mem.h"
#include "libc-base/string/str.h"
#include "libc-base/thread/spin.h"
#ifdef __cplusplus
}
#endif
