// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "libc-base/00-include.hpp"
#include "libc-base/error.hpp"
#include "libc-base/exch.hpp"
#include "libc-base/math/base.hpp"
#include "libc-base/math/bits.hpp"
#include "libc-base/math/complex/base.hpp"
#include "libc-base/math/complex/complex.hpp"
#include "libc-base/math/exp-log.hpp"
#include "libc-base/math/math.hpp"
#include "libc-base/math/sin.hpp"
#include "libc-base/math/sqrt.hpp"
#include "libc-base/math/sum.hpp"
#include "libc-base/rc.hpp"
