// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "libc/asm/asm.h"
#include "libc/asm/flag.h"
#include "libc/asm/io.h"
#include "libc/asm/reg.h"
#include "libc/asm/syscall-linux-x64.h"
#include "libc/color.h"
#include "libc/crypto/hash.h"
#include "libc/data-structure/array-list.h"
#include "libc/data-structure/avltree.h"
#include "libc/data-structure/bitmap.h"
#include "libc/data-structure/circular-buffer.h"
#include "libc/data-structure/circular-queue.h"
#include "libc/data-structure/event.h"
#include "libc/data-structure/list.h"
#include "libc/data-structure/queue-mt.h"
#include "libc/data-structure/queue.h"
#include "libc/data-structure/rbtree-strptr.h"
#include "libc/data-structure/rbtree.h"
#include "libc/data-structure/slist-strptr.h"
#include "libc/data-structure/slist.h"
#include "libc/data-structure/trie.h"
#include "libc/math/base.h"
#include "libc/math/bits.h"
#include "libc/math/complex/base.h"
#include "libc/math/exp-log.h"
#include "libc/math/float.h"
#include "libc/math/i64-div.h"
#include "libc/math/math.h"
#include "libc/math/sqrt.h"
#include "libc/stdio/print.h"
#include "libc/stdlib/alloc.h"
#include "libc/stdlib/atox.h"
#include "libc/stdlib/xtoa.h"
#include "libc/string/alloc.h"
#include "libc/string/mem.h"
#include "libc/string/str.h"
#include "libc/thread/spin.h"
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
#include "libc/math/base.hpp"
#include "libc/math/bits.hpp"
#include "libc/math/complex/base.hpp"
#include "libc/math/complex/complex.hpp"
#include "libc/math/exp-log.hpp"
#include "libc/math/math.hpp"
#include "libc/math/sin.hpp"
#include "libc/math/sqrt.hpp"
#include "libc/math/sum.hpp"
#endif
