// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "libc/include.h"
#ifdef __cplusplus
}
#endif
