// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "libplos/include-libc.h"
#include "libplos/stdio/print.h"
#ifdef __cplusplus
}
#endif
