// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "loader/8295a.h"
#include "loader/ELF/ELF.h"
#include "loader/ELF/header.h"
#include "loader/ELF/pt.h"
#include "loader/ELF/sht.h"
#include "loader/ahci.h"
#include "loader/cmos.h"
#include "loader/cpu.h"
#include "loader/dma.h"
#include "loader/fdc.h"
#include "loader/file.h"
#include "loader/fs/fat.h"
#include "loader/fs/pfs.h"
#include "loader/fs/vfs.h"
#include "loader/ide.h"
#include "loader/include-libc.h"
#include "loader/kbd.h"
#include "loader/list.h"
#include "loader/mem.h"
#include "loader/mstr.h"
#include "loader/pci.h"
#include "loader/screen.h"
#include "loader/str.h"
#include "loader/tsk.h"
#include "loader/vdisk.h"
#ifdef __cplusplus
}
#endif
