// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "loader/ELF/ELF.h"
#include "loader/ELF/header.h"
#include "loader/ELF/pt.h"
#include "loader/ELF/sht.h"
#include "loader/ctypes.h"
#include "loader/dosldr/8295a.h"
#include "loader/dosldr/ahci.h"
#include "loader/dosldr/cmos.h"
#include "loader/dosldr/cpu.h"
#include "loader/dosldr/dma.h"
#include "loader/dosldr/fdc.h"
#include "loader/dosldr/file.h"
#include "loader/dosldr/fs/fat.h"
#include "loader/dosldr/fs/pfs.h"
#include "loader/dosldr/fs/vfs.h"
#include "loader/dosldr/ide.h"
#include "loader/dosldr/include-libc.h"
#include "loader/dosldr/kbd.h"
#include "loader/dosldr/list.h"
#include "loader/dosldr/mem.h"
#include "loader/dosldr/pci.h"
#include "loader/dosldr/screen.h"
#include "loader/dosldr/str.h"
#include "loader/dosldr/tsk.h"
#include "loader/dosldr/vdisk.h"
#include "loader/mstr.h"
#include "loader/pfs.h"
#include "loader/stddef.h"
#include "loader/sys/types.h"
#ifdef __cplusplus
}
#endif
