// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "misc/00-include.h"
#include "misc/color.h"
#include "misc/crypto/codec.h"
#include "misc/crypto/hash.h"
#include "misc/file.h"
#include "misc/math/fft.h"
#include "misc/math/mdct.h"
#include "misc/stdio/print.h"
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
#include "misc/00-include.hpp"
#include "misc/math/fft.hpp"
#include "misc/math/gaussian-blur.hpp"
#include "misc/string.hpp"
#endif
