// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "misc/color.h"
#include "misc/file.h"
#include "misc/include.h"
#include "misc/math/fft.h"
#include "misc/stdio/print.h"
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
#include "misc/exch.hpp"
#include "misc/math/fft.hpp"
#endif
