// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "plmp/mpi32.h"
#include "plmp/mpi64.h"
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
#include "plmp/mpi32.hpp"
#endif
