// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "plty/fb.h"
#include "plty/plty.h"
#ifdef __cplusplus
}
#endif
