// %% generated %%
// %% include-generated %%
// This file is automatically generated, please do not modify it.
#pragma once
#include "sound/fmt.h"
#ifdef __cplusplus
extern "C" {
#endif
#include "sound/fmtconv.h"
#include "sound/mix.h"
#ifdef __cplusplus
}
#endif
