// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "sound/fmt.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
