// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "sys/osapi.h"
#include "sys/plos-syscall.h"
#ifdef __cplusplus
}
#endif
