#pragma once
#define BS_jmpBoot       0
#define BS_OEMName       3
#define BPB_BytsPerSec   11
#define BPB_SecPerClus   13
#define BPB_RsvdSecCnt   14
#define BPB_NumFATs      16
#define BPB_RootEntCnt   17
#define BPB_TotSec16     19
#define BPB_Media        21
#define BPB_FATSz16      22
#define BPB_SecPerTrk    24
#define BPB_NumHeads     26
#define BPB_HiddSec      28
#define BPB_TotSec32     32
#define BPB_FATSz32      36
#define BPB_ExtFlags     40
#define BPB_FSVer        42
#define BPB_RootClus     44
#define BPB_FSInfo       48
#define BPB_BkBootSec    50
#define BPB_Reserved     52
#define BPB_Fat32ExtByts 28
#define BS_DrvNum        36
#define BS_Reserved1     37
#define BS_BootSig       38
#define BS_VolD          39
#define BS_VolLab        43
#define BS_FileSysType   54